# Generated by Django 5.2.13 on 2026-05-16 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_number', models.CharField(max_length=10)),
                ('bike_type', models.CharField(default='Standard', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RentalsDemanddata',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('zone', models.TextField(blank=True, null=True)),
                ('is_weekend', models.IntegerField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('event_score', models.FloatField(blank=True, null=True)),
                ('commute_index', models.FloatField(blank=True, null=True)),
                ('bike_demand', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rentals_demanddata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rentals.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='rentals.zone'),
        ),
    ]
